//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/instance_type_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import { file_google_protobuf_timestamp } from "../../../google/protobuf/timestamp_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/instance_type_type.proto.
 */
export const file_osac_private_v1_instance_type_type: GenFile = /*@__PURE__*/
  fileDesc("Cihvc2FjL3ByaXZhdGUvdjEvaW5zdGFuY2VfdHlwZV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEi2AEKF0luc3RhbmNlVHlwZURlcHJlY2F0aW9uEjEKBXN0YXRlGAEgASgOMiIub3NhYy5wcml2YXRlLnYxLkluc3RhbmNlVHlwZVN0YXRlEhMKC3JlcGxhY2VtZW50GAIgASgJEjkKFWRlcHJlY2F0aW9uX3RpbWVzdGFtcBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASOgoWb2Jzb2xlc2NlbmNlX3RpbWVzdGFtcBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAirQEKDEluc3RhbmNlVHlwZRIKCgJpZBgBIAEoCRIrCghtZXRhZGF0YRgCIAEoCzIZLm9zYWMucHJpdmF0ZS52MS5NZXRhZGF0YRIvCgRzcGVjGAMgASgLMiEub3NhYy5wcml2YXRlLnYxLkluc3RhbmNlVHlwZVNwZWMSMwoGc3RhdHVzGAQgASgLMiMub3NhYy5wcml2YXRlLnYxLkluc3RhbmNlVHlwZVN0YXR1cyK8AQoQSW5zdGFuY2VUeXBlU3BlYxINCgVjb3JlcxgBIAEoBRISCgptZW1vcnlfZ2liGAIgASgFEhMKC2Rlc2NyaXB0aW9uGAMgASgJEjEKBXN0YXRlGAQgASgOMiIub3NhYy5wcml2YXRlLnYxLkluc3RhbmNlVHlwZVN0YXRlEj0KC2RlcHJlY2F0aW9uGAUgASgLMigub3NhYy5wcml2YXRlLnYxLkluc3RhbmNlVHlwZURlcHJlY2F0aW9uIhQKEkluc3RhbmNlVHlwZVN0YXR1cyqeAQoRSW5zdGFuY2VUeXBlU3RhdGUSIwofSU5TVEFOQ0VfVFlQRV9TVEFURV9VTlNQRUNJRklFRBAAEh4KGklOU1RBTkNFX1RZUEVfU1RBVEVfQUNUSVZFEAESIgoeSU5TVEFOQ0VfVFlQRV9TVEFURV9ERVBSRUNBVEVEEAISIAocSU5TVEFOQ0VfVFlQRV9TVEFURV9PQlNPTEVURRADYgZwcm90bzM", [file_google_protobuf_timestamp, file_osac_private_v1_metadata_type]);

/**
 * Contains deprecation details for an instance type.
 *
 * This message is only meaningful when the parent InstanceType state is DEPRECATED or OBSOLETE.
 * The state field mirrors the parent InstanceType spec state, making this message self-contained
 * when serialized independently.
 *
 * @generated from message osac.private.v1.InstanceTypeDeprecation
 */
export type InstanceTypeDeprecation = Message<"osac.private.v1.InstanceTypeDeprecation"> & {
  /**
   * Current deprecation state (DEPRECATED or OBSOLETE). Mirrors the spec-level state.
   *
   * @generated from field: osac.private.v1.InstanceTypeState state = 1;
   */
  state: InstanceTypeState;

  /**
   * Suggested replacement instance type name (e.g., "standard-8-32").
   *
   * @generated from field: string replacement = 2;
   */
  replacement: string;

  /**
   * When deprecation was announced. Auto-set on transition to DEPRECATED.
   *
   * @generated from field: google.protobuf.Timestamp deprecation_timestamp = 3;
   */
  deprecationTimestamp?: Timestamp | undefined;

  /**
   * When the instance type becomes or became obsolete. Admin-specified or auto-set on transition to OBSOLETE.
   *
   * @generated from field: google.protobuf.Timestamp obsolescence_timestamp = 4;
   */
  obsolescenceTimestamp?: Timestamp | undefined;
};

/**
 * Describes the message osac.private.v1.InstanceTypeDeprecation.
 * Use `create(InstanceTypeDeprecationSchema)` to create a new message.
 */
export const InstanceTypeDeprecationSchema: GenMessage<InstanceTypeDeprecation> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_instance_type_type, 0);

/**
 * Contains the details about the instance type that are available only for the system.
 *
 * Instance types are admin-managed catalog resources that define pre-configured compute bundles
 * (cores, memory) referenced by name when creating VMs. Cloud Provider Admins control the available
 * configurations through lifecycle-managed instance types.
 *
 * The `spec` contains the desired configuration, and may be modified by the admin. The `status` contains the
 * current state of the instance type, is provided by the system and can't be modified by the user.
 *
 * @generated from message osac.private.v1.InstanceType
 */
export type InstanceType = Message<"osac.private.v1.InstanceType"> & {
  /**
   * Unique identifier of the instance type.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the instance type, including name, labels, tenant, and timestamps.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the instance type (admin-modifiable).
   *
   * @generated from field: osac.private.v1.InstanceTypeSpec spec = 3;
   */
  spec?: InstanceTypeSpec | undefined;

  /**
   * Current state of the instance type (system-provided, read-only).
   *
   * @generated from field: osac.private.v1.InstanceTypeStatus status = 4;
   */
  status?: InstanceTypeStatus | undefined;
};

/**
 * Describes the message osac.private.v1.InstanceType.
 * Use `create(InstanceTypeSchema)` to create a new message.
 */
export const InstanceTypeSchema: GenMessage<InstanceType> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_instance_type_type, 1);

/**
 * Defines the desired configuration for an InstanceType.
 *
 * The spec contains admin-specified parameters that define the compute bundle. The `cores` and `memory_gib`
 * fields are immutable after creation. The `description`, `state`, and `deprecation` fields may be updated
 * to manage the instance type lifecycle.
 *
 * @generated from message osac.private.v1.InstanceTypeSpec
 */
export type InstanceTypeSpec = Message<"osac.private.v1.InstanceTypeSpec"> & {
  /**
   * Number of CPU cores. Immutable after creation.
   *
   * @generated from field: int32 cores = 1;
   */
  cores: number;

  /**
   * Amount of memory in GiB. Immutable after creation.
   *
   * @generated from field: int32 memory_gib = 2;
   */
  memoryGib: number;

  /**
   * Human friendly description of the instance type, using Markdown format.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Current lifecycle state of the instance type.
   *
   * @generated from field: osac.private.v1.InstanceTypeState state = 4;
   */
  state: InstanceTypeState;

  /**
   * Deprecation details. Only meaningful when state is DEPRECATED or OBSOLETE.
   *
   * @generated from field: osac.private.v1.InstanceTypeDeprecation deprecation = 5;
   */
  deprecation?: InstanceTypeDeprecation | undefined;
};

/**
 * Describes the message osac.private.v1.InstanceTypeSpec.
 * Use `create(InstanceTypeSpecSchema)` to create a new message.
 */
export const InstanceTypeSpecSchema: GenMessage<InstanceTypeSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_instance_type_type, 2);

/**
 * Contains the system-provided status of an InstanceType.
 *
 * Currently empty. Reserved for future reconciliation state.
 *
 * @generated from message osac.private.v1.InstanceTypeStatus
 */
export type InstanceTypeStatus = Message<"osac.private.v1.InstanceTypeStatus"> & {
};

/**
 * Describes the message osac.private.v1.InstanceTypeStatus.
 * Use `create(InstanceTypeStatusSchema)` to create a new message.
 */
export const InstanceTypeStatusSchema: GenMessage<InstanceTypeStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_instance_type_type, 3);

/**
 * Lifecycle states for InstanceType resources.
 *
 * @generated from enum osac.private.v1.InstanceTypeState
 */
export enum InstanceTypeState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: INSTANCE_TYPE_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The instance type is fully available for new VM creation.
   *
   * @generated from enum value: INSTANCE_TYPE_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * The instance type is available with warnings; migration to a replacement is recommended.
   *
   * @generated from enum value: INSTANCE_TYPE_STATE_DEPRECATED = 2;
   */
  DEPRECATED = 2,

  /**
   * The instance type is not available for new VMs; visible for lookups only.
   *
   * @generated from enum value: INSTANCE_TYPE_STATE_OBSOLETE = 3;
   */
  OBSOLETE = 3,
}

/**
 * Describes the enum osac.private.v1.InstanceTypeState.
 */
export const InstanceTypeStateSchema: GenEnum<InstanceTypeState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_instance_type_type, 0);

