//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/metadata_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import { file_google_protobuf_timestamp } from "../../../google/protobuf/timestamp_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/metadata_type.proto.
 */
export const file_osac_private_v1_metadata_type: GenFile = /*@__PURE__*/
  fileDesc("CiNvc2FjL3ByaXZhdGUvdjEvbWV0YWRhdGFfdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIuwDCghNZXRhZGF0YRI2ChJjcmVhdGlvbl90aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjYKEmRlbGV0aW9uX3RpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEgoKZmluYWxpemVycxgDIAMoCRIPCgdjcmVhdG9yGAQgASgJEg4KBnRlbmFudBgFIAEoCRI+CgRuYW1lGAYgASgJQjC6SC1yKxg/MideKFthLXowLTldKFthLXowLTktXXswLDYxfVthLXowLTldKT8pPyQSNQoGbGFiZWxzGAcgAygLMiUub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhLkxhYmVsc0VudHJ5Ej8KC2Fubm90YXRpb25zGAggAygLMioub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhLkFubm90YXRpb25zRW50cnkSDwoHdmVyc2lvbhgJIAEoBRIPCgdwcm9qZWN0GAogASgJGi0KC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaMgoQQW5ub3RhdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * Metadata common to all kinds of objects.
 *
 * @generated from message osac.private.v1.Metadata
 */
export type Metadata = Message<"osac.private.v1.Metadata"> & {
  /**
   * Time of creation of the object.
   *
   * @generated from field: google.protobuf.Timestamp creation_timestamp = 1;
   */
  creationTimestamp?: Timestamp | undefined;

  /**
   * Time of deletion of the object.
   *
   * @generated from field: google.protobuf.Timestamp deletion_timestamp = 2;
   */
  deletionTimestamp?: Timestamp | undefined;

  /**
   * Finalizers indicate tasks that need to be completed before the object can be completely deleted. When the object
   * has been deleted and this list is empty the system will automatically archive the object.
   *
   * @generated from field: repeated string finalizers = 3;
   */
  finalizers: string[];

  /**
   * Creator contains the identifier of the user or group that created the object.
   *
   * @generated from field: string creator = 4;
   */
  creator: string;

  /**
   * Tenant contains the identifier of the tenant that the object belongs to.
   *
   * @generated from field: string tenant = 5;
   */
  tenant: string;

  /**
   * Human friendly name of the object.
   *
   * Has the same restrictions than DNS labels, as described in RFC 1035:
   *
   * - Must be between 1 and 63 characters long.
   * - Must only contain letters (a-z), digits (0-9) and hyphens (-).
   * - It isn't case sensitive.
   *
   * It is optional and not unique, so multiple objecs, even created by the same user or tenant, can have the same name.
   *
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * Labels contains key-value pairs for organizing and selecting objects.
   *
   * Keys consist of an optional prefix and a name separated by '/':
   *
   * - Prefix is a DNS subdomain (RFC 1035) and must be between 1 and 253 characters long.
   * - Name must be between 1 and 63 characters long, start and end with an alphanumeric character, and contain only
   *   letters (a-z), digits (0-9), '-' '_' or '.'.
   *
   * Values are optional; when present they must be between 0 and 63 characters long and follow the same character
   * rules as names.
   *
   * Labels are indexed and searchable.
   *
   * @generated from field: map<string, string> labels = 7;
   */
  labels: { [key: string]: string };

  /**
   * Annotations contains arbitrary metadata for objects.
   *
   * Keys follow the same rules as label keys, including the optional DNS subdomain prefix and the 1-63 character name
   * restrictions. Values can be any string.
   *
   * @generated from field: map<string, string> annotations = 8;
   */
  annotations: { [key: string]: string };

  /**
   * Version is a numeric field that is automatically incremented with every change to the object.
   *
   * @generated from field: int32 version = 9;
   */
  version: number;

  /**
   * Full name of the project that the object is assigned to. It can be empty, which means the object belongs to
   * the default project of the tenant.
   *
   * When not empty, the value is a dot-separated path of labels representing a hierarchy of projects. For example,
   * `team-a.frontend.staging` represents a project nested three levels deep.
   *
   * Each label in the path has the same restrictions as DNS labels, as described in RFC 1035:
   *
   * - Must be between 1 and 63 characters long.
   * - Must only contain letters (a-z), digits (0-9) and hyphens (-).
   * - It isn't case sensitive.
   *
   * For project objects this field represents the parent project. For example, if a project named `frontend` has
   * this field set to `team-a`, it means that `frontend` is a child of the `team-a` project, and its full name is
   * `team-a.frontend`.
   *
   * For organization objects this field is always empty, as organizations don't belong to a project.
   *
   * @generated from field: string project = 10;
   */
  project: string;
};

/**
 * Describes the message osac.private.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_metadata_type, 0);

