//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/nat_gateway_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/nat_gateway_type.proto.
 */
export const file_osac_private_v1_nat_gateway_type: GenFile = /*@__PURE__*/
  fileDesc("CiZvc2FjL3ByaXZhdGUvdjEvbmF0X2dhdGV3YXlfdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIqcBCgpOQVRHYXRld2F5EgoKAmlkGAEgASgJEisKCG1ldGFkYXRhGAIgASgLMhkub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhEi0KBHNwZWMYAyABKAsyHy5vc2FjLnByaXZhdGUudjEuTkFUR2F0ZXdheVNwZWMSMQoGc3RhdHVzGAQgASgLMiEub3NhYy5wcml2YXRlLnYxLk5BVEdhdGV3YXlTdGF0dXMiTgoOTkFUR2F0ZXdheVNwZWMSHwoPdmlydHVhbF9uZXR3b3JrGAEgASgJQgbgQQLgQQUSGwoLZXh0ZXJuYWxfaXAYAiABKAlCBuBBAuBBBSKBAQoQTkFUR2F0ZXdheVN0YXR1cxI0CgVzdGF0ZRgBIAEoDjIgLm9zYWMucHJpdmF0ZS52MS5OQVRHYXRld2F5U3RhdGVCA+BBAxIZCgdtZXNzYWdlGAIgASgJQgPgQQNIAIgBARIQCgNodWIYAyABKAlCA+BBA0IKCghfbWVzc2FnZSquAQoPTkFUR2F0ZXdheVN0YXRlEiEKHU5BVF9HQVRFV0FZX1NUQVRFX1VOU1BFQ0lGSUVEEAASHQoZTkFUX0dBVEVXQVlfU1RBVEVfUEVORElORxABEhsKF05BVF9HQVRFV0FZX1NUQVRFX1JFQURZEAISHAoYTkFUX0dBVEVXQVlfU1RBVEVfRkFJTEVEEAMSHgoaTkFUX0dBVEVXQVlfU1RBVEVfREVMRVRJTkcQBGIGcHJvdG8z", [file_google_api_field_behavior, file_osac_private_v1_metadata_type]);

/**
 * Represents a NAT gateway for outbound traffic (SNAT) from a VirtualNetwork.
 *
 * A NATGateway provides a dedicated egress identity for all resources within a VirtualNetwork.
 * All outbound traffic from the VirtualNetwork's CIDR is source-NATted to the associated
 * ExternalIP address. This gives tenants a known, stable source IP for egress traffic —
 * useful for allowlisting, auditing, and compliance.
 *
 * NATGateway handles outbound traffic only (SNAT). Inbound traffic (DNAT) is handled by
 * ExternalIPAttachment. An ExternalIP can only be used by one consumer — either a NATGateway
 * or an ExternalIPAttachment, not both.
 *
 * One NATGateway is allowed per VirtualNetwork. Creating a second NATGateway for the same
 * VirtualNetwork is rejected. All spec fields are immutable after creation.
 *
 * The lifecycle follows: PENDING (SNAT rule being configured) -> READY (egress active).
 * FAILED is a terminal error state. DELETING is set during deprovisioning.
 *
 * @generated from message osac.private.v1.NATGateway
 */
export type NATGateway = Message<"osac.private.v1.NATGateway"> & {
  /**
   * Unique identifier of the NAT gateway.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the NAT gateway, including name, labels, and timestamps.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the NAT gateway (user-specified).
   *
   * @generated from field: osac.private.v1.NATGatewaySpec spec = 3;
   */
  spec?: NATGatewaySpec | undefined;

  /**
   * Current state of the NAT gateway (system-provided, read-only).
   *
   * @generated from field: osac.private.v1.NATGatewayStatus status = 4;
   */
  status?: NATGatewayStatus | undefined;
};

/**
 * Describes the message osac.private.v1.NATGateway.
 * Use `create(NATGatewaySchema)` to create a new message.
 */
export const NATGatewaySchema: GenMessage<NATGateway> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_nat_gateway_type, 0);

/**
 * Defines the desired configuration for a NATGateway.
 *
 * Both fields are required and immutable after creation. The virtual_network identifies which
 * VirtualNetwork's egress traffic is NATted, and the external_ip provides the source address
 * for outbound connections.
 *
 * @generated from message osac.private.v1.NATGatewaySpec
 */
export type NATGatewaySpec = Message<"osac.private.v1.NATGatewaySpec"> & {
  /**
   * Parent VirtualNetwork ID. Required and immutable after creation.
   *
   * Must reference the ID of an existing VirtualNetwork. All outbound traffic from subnets
   * within this VirtualNetwork will be source-NATted to the associated ExternalIP address.
   * Only one NATGateway is allowed per VirtualNetwork.
   *
   * Example: "019728a4-3f5c-7def-8abc-1234567890ab"
   *
   * @generated from field: string virtual_network = 1;
   */
  virtualNetwork: string;

  /**
   * ExternalIP ID to use as the SNAT source address. Required and immutable after creation.
   *
   * Must reference the ID of an existing ExternalIP in ALLOCATED state. The ExternalIP must
   * not already be consumed by another NATGateway or ExternalIPAttachment. The allocated
   * address from this ExternalIP becomes the source IP for all egress traffic from the
   * VirtualNetwork.
   *
   * Example: "019728a4-4e6d-7abc-9def-abcdef012345"
   *
   * @generated from field: string external_ip = 2;
   */
  externalIp: string;
};

/**
 * Describes the message osac.private.v1.NATGatewaySpec.
 * Use `create(NATGatewaySpecSchema)` to create a new message.
 */
export const NATGatewaySpecSchema: GenMessage<NATGatewaySpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_nat_gateway_type, 1);

/**
 * Represents the current operational state of a NATGateway.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the system
 * updates them based on reconciliation of the spec and feedback from the cluster controller.
 *
 * @generated from message osac.private.v1.NATGatewayStatus
 */
export type NATGatewayStatus = Message<"osac.private.v1.NATGatewayStatus"> & {
  /**
   * Current lifecycle state of the NAT gateway.
   *
   * @generated from field: osac.private.v1.NATGatewayState state = 1;
   */
  state: NATGatewayState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, may contain progress information like "Configuring SNAT rule".
   * For FAILED state, contains the error details. Typically empty for READY state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;

  /**
   * Identifier of the hub cluster that this NAT gateway is deployed to.
   *
   * Set by the fulfillment-service controller when reconciling the NAT gateway to a Kubernetes CR
   * on the target hub cluster. Used for tracking which cluster the networking resources reside on.
   *
   * @generated from field: string hub = 3;
   */
  hub: string;
};

/**
 * Describes the message osac.private.v1.NATGatewayStatus.
 * Use `create(NATGatewayStatusSchema)` to create a new message.
 */
export const NATGatewayStatusSchema: GenMessage<NATGatewayStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_nat_gateway_type, 2);

/**
 * Lifecycle states for NATGateway resources.
 *
 * State transitions: UNSPECIFIED -> PENDING -> READY. On deletion: READY -> DELETING.
 * FAILED is a terminal error state for provisioning failures.
 *
 * @generated from enum osac.private.v1.NATGatewayState
 */
export enum NATGatewayState {
  /**
   * State is unknown or has not been determined yet. Default state before initialization.
   *
   * @generated from enum value: NAT_GATEWAY_STATE_UNSPECIFIED = 0;
   */
  NAT_GATEWAY_STATE_UNSPECIFIED = 0,

  /**
   * The NAT gateway is being provisioned.
   *
   * During this state, the system is configuring the SNAT rule on the fabric manager
   * for the VirtualNetwork's CIDR, using the associated ExternalIP as the source address.
   *
   * @generated from enum value: NAT_GATEWAY_STATE_PENDING = 1;
   */
  NAT_GATEWAY_STATE_PENDING = 1,

  /**
   * The NAT gateway is active and egress traffic is being NATted.
   *
   * The SNAT rule is configured and all outbound traffic from the VirtualNetwork's CIDR
   * is source-NATted to the associated ExternalIP address. The NAT gateway applies to
   * all resources in the VirtualNetwork — VMs, BM servers, and cluster nodes.
   *
   * @generated from enum value: NAT_GATEWAY_STATE_READY = 2;
   */
  NAT_GATEWAY_STATE_READY = 2,

  /**
   * Provisioning failed. Check status.message for error details.
   *
   * This is a terminal error state. The NATGateway may require manual intervention
   * (e.g., deleting and recreating) or a Signal RPC to retry the operation.
   *
   * @generated from enum value: NAT_GATEWAY_STATE_FAILED = 3;
   */
  NAT_GATEWAY_STATE_FAILED = 3,

  /**
   * The NAT gateway is being deprovisioned and will be removed.
   *
   * On deletion of a NATGateway, the system removes the SNAT rule from the fabric manager.
   * The associated ExternalIP is released for use by other resources. The resource remains
   * visible in this state until fully cleaned up.
   *
   * @generated from enum value: NAT_GATEWAY_STATE_DELETING = 4;
   */
  NAT_GATEWAY_STATE_DELETING = 4,
}

/**
 * Describes the enum osac.private.v1.NATGatewayState.
 */
export const NATGatewayStateSchema: GenEnum<NATGatewayState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_nat_gateway_type, 0);

