//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/storage_tier_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/storage_tier_type.proto.
 */
export const file_osac_private_v1_storage_tier_type: GenFile = /*@__PURE__*/
  fileDesc("Cidvc2FjL3ByaXZhdGUvdjEvc3RvcmFnZV90aWVyX3R5cGUucHJvdG8SD29zYWMucHJpdmF0ZS52MSLMAQoSQmFja2VuZEFzc29jaWF0aW9uEhIKCmJhY2tlbmRfaWQYASABKAkSMgoIcHJvdG9jb2wYAiABKA4yIC5vc2FjLnByaXZhdGUudjEuU3RvcmFnZVByb3RvY29sEh4KFm1heF9yZWFkX2JhbmR3aWR0aF9tYnMYAyABKAUSHwoXbWF4X3dyaXRlX2JhbmR3aWR0aF9tYnMYBCABKAUSEQoJcXVvdGFfZ2liGAUgASgDEhoKEmVuY3J5cHRpb25fZW5hYmxlZBgGIAEoCCKqAQoLU3RvcmFnZVRpZXISCgoCaWQYASABKAkSKwoIbWV0YWRhdGEYAiABKAsyGS5vc2FjLnByaXZhdGUudjEuTWV0YWRhdGESLgoEc3BlYxgDIAEoCzIgLm9zYWMucHJpdmF0ZS52MS5TdG9yYWdlVGllclNwZWMSMgoGc3RhdHVzGAQgASgLMiIub3NhYy5wcml2YXRlLnYxLlN0b3JhZ2VUaWVyU3RhdHVzIl0KD1N0b3JhZ2VUaWVyU3BlYxITCgtkZXNjcmlwdGlvbhgBIAEoCRI1CghiYWNrZW5kcxgCIAMoCzIjLm9zYWMucHJpdmF0ZS52MS5CYWNrZW5kQXNzb2NpYXRpb24iZwoRU3RvcmFnZVRpZXJTdGF0dXMSMAoFc3RhdGUYASABKA4yIS5vc2FjLnByaXZhdGUudjEuU3RvcmFnZVRpZXJTdGF0ZRIUCgdtZXNzYWdlGAIgASgJSACIAQFCCgoIX21lc3NhZ2UqaQoPU3RvcmFnZVByb3RvY29sEiAKHFNUT1JBR0VfUFJPVE9DT0xfVU5TUEVDSUZJRUQQABIYChRTVE9SQUdFX1BST1RPQ09MX05GUxABEhoKFlNUT1JBR0VfUFJPVE9DT0xfQkxPQ0sQAipVChBTdG9yYWdlVGllclN0YXRlEiIKHlNUT1JBR0VfVElFUl9TVEFURV9VTlNQRUNJRklFRBAAEh0KGVNUT1JBR0VfVElFUl9TVEFURV9BQ1RJVkUQAWIGcHJvdG8z", [file_osac_private_v1_metadata_type]);

/**
 * Represents the association of a storage backend within a storage tier, including protocol-specific
 * configuration and quota limits.
 *
 * @generated from message osac.private.v1.BackendAssociation
 */
export type BackendAssociation = Message<"osac.private.v1.BackendAssociation"> & {
  /**
   * Unique identifier of the associated storage backend.
   *
   * @generated from field: string backend_id = 1;
   */
  backendId: string;

  /**
   * Storage protocol used for this backend association.
   *
   * @generated from field: osac.private.v1.StorageProtocol protocol = 2;
   */
  protocol: StorageProtocol;

  /**
   * Maximum read bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_read_bandwidth_mbs = 3;
   */
  maxReadBandwidthMbs: number;

  /**
   * Maximum write bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_write_bandwidth_mbs = 4;
   */
  maxWriteBandwidthMbs: number;

  /**
   * Storage quota in gibibytes (GiB) allocated to this backend association.
   *
   * @generated from field: int64 quota_gib = 5;
   */
  quotaGib: bigint;

  /**
   * Whether data at rest is encrypted on this backend.
   *
   * @generated from field: bool encryption_enabled = 6;
   */
  encryptionEnabled: boolean;
};

/**
 * Describes the message osac.private.v1.BackendAssociation.
 * Use `create(BackendAssociationSchema)` to create a new message.
 */
export const BackendAssociationSchema: GenMessage<BackendAssociation> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 0);

/**
 * Represents a storage tier in the OSAC platform.
 *
 * StorageTier is a platform-scoped entity that groups one or more StorageBackend associations with
 * protocol, bandwidth, quota, and encryption settings. It is managed exclusively by Cloud Provider
 * Admins through the private API. Tenants consume storage tiers indirectly when provisioning
 * storage-enabled resources.
 *
 * StorageTier follows the NetworkClass pattern: DB-backed with no Kubernetes CRD and no reconciler.
 *
 * @generated from message osac.private.v1.StorageTier
 */
export type StorageTier = Message<"osac.private.v1.StorageTier"> & {
  /**
   * Unique identifier of the storage tier.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the storage tier.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the storage tier (admin-modifiable).
   *
   * @generated from field: osac.private.v1.StorageTierSpec spec = 3;
   */
  spec?: StorageTierSpec | undefined;

  /**
   * Current operational status of the storage tier.
   *
   * @generated from field: osac.private.v1.StorageTierStatus status = 4;
   */
  status?: StorageTierStatus | undefined;
};

/**
 * Describes the message osac.private.v1.StorageTier.
 * Use `create(StorageTierSchema)` to create a new message.
 */
export const StorageTierSchema: GenMessage<StorageTier> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 1);

/**
 * Defines the desired configuration for a StorageTier.
 *
 * @generated from message osac.private.v1.StorageTierSpec
 */
export type StorageTierSpec = Message<"osac.private.v1.StorageTierSpec"> & {
  /**
   * Human-readable description of the storage tier.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * List of backend associations that compose this storage tier.
   *
   * @generated from field: repeated osac.private.v1.BackendAssociation backends = 2;
   */
  backends: BackendAssociation[];
};

/**
 * Describes the message osac.private.v1.StorageTierSpec.
 * Use `create(StorageTierSpecSchema)` to create a new message.
 */
export const StorageTierSpecSchema: GenMessage<StorageTierSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 2);

/**
 * Represents the current operational state of a StorageTier.
 *
 * @generated from message osac.private.v1.StorageTierStatus
 */
export type StorageTierStatus = Message<"osac.private.v1.StorageTierStatus"> & {
  /**
   * Current lifecycle state of the storage tier.
   *
   * @generated from field: osac.private.v1.StorageTierState state = 1;
   */
  state: StorageTierState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.private.v1.StorageTierStatus.
 * Use `create(StorageTierStatusSchema)` to create a new message.
 */
export const StorageTierStatusSchema: GenMessage<StorageTierStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 3);

/**
 * Identifies the storage protocol used by a backend association within a storage tier.
 *
 * @generated from enum osac.private.v1.StorageProtocol
 */
export enum StorageProtocol {
  /**
   * Protocol is unknown or has not been specified.
   *
   * @generated from enum value: STORAGE_PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * NFS (Network File System) protocol for file-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_NFS = 1;
   */
  NFS = 1,

  /**
   * Block storage protocol for volume-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_BLOCK = 2;
   */
  BLOCK = 2,
}

/**
 * Describes the enum osac.private.v1.StorageProtocol.
 */
export const StorageProtocolSchema: GenEnum<StorageProtocol> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_storage_tier_type, 0);

/**
 * Lifecycle states for StorageTier resources.
 *
 * @generated from enum osac.private.v1.StorageTierState
 */
export enum StorageTierState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: STORAGE_TIER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The storage tier is active and available for use by tenants.
   *
   * @generated from enum value: STORAGE_TIER_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,
}

/**
 * Describes the enum osac.private.v1.StorageTierState.
 */
export const StorageTierStateSchema: GenEnum<StorageTierState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_storage_tier_type, 1);

